services:
  portainer:
    container_name: 00-portainer
    image: portainer/portainer-ce:lts
    restart: always
    env_file:
      - /secrets/globals.env
    volumes:
      - /var/docker-configs:/var/docker-configs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${GLOBAL_VOLUMES_PATH}/portainer/data:/data
    ports:
      - 9443:9443
